### ISSUE TITLE
Make error messages for title and commit checks respectively configurable 

### ISSUE THREAD

**Issue by xstefank** [xstefank/tyr#20]
Add optional message parameter to `title` and `commit` configuration

Example:
```
format:
  title:
    pattern: ".*"
    message: "Custom error message to be showed"
```
